name: feastflow-staging

services:
  api:
    environment:
      APP_ENV: staging
    ports:
      - 127.0.0.1:5210:3000

  restaurant-admin:
    ports:
      - 127.0.0.1:5211:3000

  superadmin:
    ports:
      - 127.0.0.1:5212:3000

  customer:
    ports:
      - 127.0.0.1:5213:3000

  landing:
    ports:
      - 127.0.0.1:5214:3000
