ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'GROUP_ORDER_PARTICIPANT_COMPLETED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'GROUP_ORDER_ALL_PARTICIPANTS_COMPLETED';
ALTER TYPE "GroupOrderParticipantStatus" ADD VALUE IF NOT EXISTS 'COMPLETED';
