export enum PaymentMethodEnum {
  COD = 'COD',
  STRIPE = 'STRIPE',
  PAYPAL = 'PAYPAL',
  CARD_ON_DELIVERY = 'CARD_ON_DELIVERY',
  EASYPAISA = 'EASYPAISA',
  JAZZCASH = 'JAZZCASH',
  BANK_TRANSFER = 'BANK_TRANSFER',
  WALLET = 'WALLET',
}
